name: ASC-1.3 Integrity

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  merge_group:
    types: [checks_requested]

jobs:
  governance:
    name: Governance Check
    runs-on: self-hosted

jobs:
  governance:
    name: Governance Check
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Verify Codeowners
        run: |
          if [ ! -f .github/CODEOWNERS ]; then
            echo "::error::CODEOWNERS file missing. Violation of Tier 0 Governance."
            exit 1
          fi

  system-integrity:
    name: Nix Flake Verification
    runs-on: self-hosted
    needs: governance
    steps:
      - uses: actions/checkout@v4
      - name: Hardware Syntax Check
        run: nix flake check --show-trace